from enum import Enum

class ErrorCode(Enum):

    OK = 1
    INVALID_FORMAT = 2
    UNEXPECTED_ARGUMENT = 3
    INVALID_ARGUMENT_NAME = 4
    MISSING_STRING = 5
    MISSING_INTEGER = 6
    INVALID_INTEGER = 7
    MISSING_DOUBLE = 8
    INVALID_DOUBLE = 9